# Generated by Django 3.0.7 on 2020-06-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date',
            field=models.CharField(max_length=255),
        ),
    ]
