# Generated by Django 3.0.7 on 2020-06-14 08:07

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200614_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_file',
            field=models.ImageField(null=True, upload_to=core.models.image_file_path),
        ),
    ]
